# Generated by Django 4.2.15 on 2025-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True)),
                ('dsc', models.TextField(max_length=415)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cheat_images')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
